CREATE DATABASE learning;
USE LEARNING;

SELECT * FROM Superstore;

SELECT ORDER_ID, CUSTOMER_NAME, COUNTRY FROM Superstore;
SELECT DISTINCT CUSTOMER_NAME FROM Superstore;
SELECT COUNT(DISTINCT CUSTOMER_NAME) FROM Superstore;

SELECT COUNT(*) AS DISTINCTCOUSTOMER_NAME
FROM (SELECT DISTINCT CUSTOMER_NAME FROM Superstore) SUPERSTORE;

SELECT CUSTOMER_NAME,Discount, Region FROM Superstore
WHERE SALES != 10;

SELECT CUSTOMER_NAME,Discount, Profit, Region FROM Superstore
WHERE Sales BETWEEN 2 AND 10;

SELECT * FROM Superstore
WHERE REGION IN ('SOUTH', 'WEST');

SELECT * FROM Superstore
ORDER BY Ship_Mode;

SELECT TOP 20 SUM(SALES) FROM SUPERSTORE
WHERE STATE IN ( 'TEXAS', 'KENTUCKY', 'FLORIDA', 'NEW YORK')
ORDER BY SUM(Sales) DESC;

SELECT Customer_ID, Region, SALES, PROFIT, Ship_Mode FROM Superstore
ORDER BY State, City;

SELECT * FROM Superstore
WHERE SALES > 100 AND STATE IN ( 'OHIO', 'WISCOSIN', 'FLORIDA', 'NEW YORK') AND Customer_Name LIKE '%AR%';

SELECT * FROM Superstore
WHERE Ship_Mode = 'FIRST CLASS' AND  Region = 'WEST'; 220.046

SELECT * FROM Superstore
WHERE Ship_Mode = 'FIRST CLASS' AND (SEGMENT = 'CONSUMER' OR Segment = 'CORPORATE') AND Region = 'WEST';

SELECT * FROM Superstore
WHERE Sub_Category = 'ART' OR Product_Name = 'Prang Colored Pencils' ;

SELECT Customer_Name, Region, Order_ID, STATE, Sales FROM Superstore
WHERE  NOT STATE IN ('FLORIDA', 'ARIZONIA', 'TEXAS','CALIFORNIA') AND Sales > 1000
ORDER BY SALES DESC;

SELECT * FROM Superstore
WHERE STATE NOT IN ('FLORIDA', 'ARIZONIA', 'TEXAS','CALIFORNIA');

SELECT Profit FROM Superstore
WHERE Profit IS NULL;

/*-- REMOVE NULL VALUE IN THE PROFIT COLUMN BY REPLACING WITH AVERAGE PROFIT*/
UPDATE SUPERSTORE SET Profit = 28.7017933364272
WHERE Profit IS NULL;

SELECT TOP 10 CUSTOMER_NAME, SALES, PROFIT, Discount, State, CITY, Region FROM Superstore
WHERE SALES > 8000
ORDER BY SALES DESC;

/* HIGHEST SALES AND PROFIT GENERATED */
SELECT CUSTOMER_NAME, MAX(SALES) FROM SUPERSTORE
GROUP BY Customer_Name
ORDER BY max(sales) desc;

SELECT MAX(PROFIT) FROM Superstore;

SELECT MIN(SALES) LOWEST_SALES FROM Superstore;
SELECT MIN(PROFIT) LOWEST_PROFIT FROM Superstore;

SELECT MAX(SALES) FROM SUPERSTORE
WHERE STATE = 'NEW YORK';

SELECT COUNT(*) FROM Superstore;
SELECT COUNT(CUSTOMER_NAME) FROM Superstore;
SELECT COUNT(STATE) FROM SUPERSTORE
WHERE STATE = 'NEW YORK';

ALTER TABLE Superstore ADD Total_Cost DECIMAL(18,2);
SELECT SALES - PROFIT AS [TOTAL COST] FROM Superstore;
ALTER TABLE Superstore DROP COLUMN Total_Cost;

UPDATE Superstore SET Total_COST = SALES - PROFIT
WHERE Total_Cost IS NULL;

SELECT COUNT(Sub_Category) NUMBER_OF_RECORD FROM Superstore
WHERE SALES < 8000 OR STATE = 'TEXAS';

SELECT COUNT(*) AS [Number of records], Customer_Name, CUSTOMER_ID FROM Superstore
WHERE STATE = 'Wisconsin'
GROUP BY Customer_ID, Customer_Name;

SELECT COUNT(DISTINCT STATE) [NUMBER OF RECORDS], Customer_Name, Customer_ID FROM Superstore
GROUP BY Customer_Name, Customer_ID
ORDER BY COUNT(DISTINCT STATE) DESC;

/* NUMNBER OF TRANSACTION OF EACH CUSTOMER NAME IN EACH STATE */
SELECT STATE, CUSTOMER_NAME, CUSTOMER_ID, COUNT(DISTINCT Customer_ID) [Number of unique records], 
COUNT(*) [Total number of records] FROM Superstore
GROUP BY STATE, Customer_Name, Customer_ID
ORDER BY STATE, [Total number of records] DESC;

SELECT TOP 10 CUSTOMER_NAME, CUSTOMER_ID, STRING_AGG(STATE, ', ') STATES,
COUNT(*) [Total number of records] FROM Superstore
GROUP BY Customer_Name, Customer_ID
ORDER BY[Total number of records] DESC;

/* USING CTE */
WITH DISTINCTSTATES AS (SELECT DISTINCT CUSTOMER_NAME, CUSTOMER_ID, STATE FROM SUPERSTORE) 
SELECT TOP 50 CUSTOMER_NAME, CUSTOMER_ID, STRING_AGG(STATE, ', ') STATES,
(SELECT COUNT(*) FROM Superstore S WHERE S.Customer_ID = D.Customer_ID) AS [Total number of records]
FROM DISTINCTSTATES D
GROUP BY Customer_Name, Customer_ID
ORDER BY[Total number of records] DESC;

SELECT SUM(SALES) [Total sales ], Region FROM Superstore
WHERE Sub_Category = 'CHAIRS'
GROUP BY Region;

SELECT SUM(PROFIT) [Total Profit], Ship_Mode FROM Superstore
WHERE SALES BETWEEN 1500 AND 10000
GROUP BY Ship_Mode
ORDER BY SUM(PROFIT) DESC;

SELECT SUM(PROFIT) [Total Profit], Ship_Mode FROM Superstore
WHERE Region = 'SOUTH'
GROUP BY Ship_Mode
ORDER BY SUM(PROFIT) DESC;

SELECT AVG(SALES) FROM Superstore;
SELECT AVG(PROFIT) FROM Superstore;
SELECT * FROM SUPERSTORE;
SELECT Order_Date FROM Superstore
WHERE Order_Date = 'YYYY';

SELECT SHIP_DATE, SHIP_MODE, AVG(PROFIT) [Average profit] FROM Superstore
WHERE STATE = 'CALIFORNIA'
GROUP BY Ship_Date, Ship_Mode;

SELECT * FROM Superstore;
SELECT Profit FROM Superstore
WHERE Profit IS NULL;

/* COUNT OF ORDER RECEIVED */
SELECT COUNT(DISTINCT Order_ID) Orders FROM SUPERSTORE;

/* TOTAL REVENUE GENERATED */
SELECT ROUND(SUM(SALES), 2) [TOTAL REVENUE] FROM Superstore;

/* TOTAL PROFIT GENERATED */
SELECT ROUND(SUM(PROFIT), 2) [TOTAL PROFIT] FROM SUPERSTORE;

/* AVERAGE TOTAL SALES PER ORDER */ 
 SELECT ROUND(AVG(TOTAL_ORDER_SALES), 2) [AVERAGE SALES] FROM 
 (SELECT Order_ID, SUM(SALES) [TOTAL_ORDER_SALES] FROM SUPERSTORE 
 GROUP BY Order_ID) AS ORDER_SALES;

 SELECT ORDER_ID, COUNT(*) [ROW COUNT] FROM Superstore
 GROUP BY Order_ID
 HAVING COUNT(*) >1;

 SELECT ORDER_ID, SALES FROM SUPERSTORE 
 WHERE Order_ID = 'CA-2016-152156';

 /* TOTAL DISCOUNT GIVEN */
 SELECT ROUND(SUM(DISCOUNT), 2) [TOTAL DISCOUNT] FROM Superstore;

 /* TOTAL QUANTITY ORDERED */
 SELECT SUM(QUANTITY) [TOTAL QUANTITY] FROM Superstore;

 /* TOTAL REVENUE GENERATED ACROSS EACH REGION */
 SELECT REGION, ROUND(SUM(SALES), 2) [TOTAL REVENUE ] FROM Superstore
 GROUP BY Region
 ORDER BY SUM(SALES) DESC;

 /* TOTAL PROFIT GENERATED ACROSS EACH REGION */
 SELECT REGION, ROUND(SUM(PROFIT), 2) [TOTAL PROFIT] FROM Superstore
 GROUP BY Region
 ORDER BY SUM(PROFIT) DESC;

 /* TOTAL REVENUE GENERATED SHIP MODE */
 SELECT SHIP_MODE, ROUND(SUM(SALES), 2) [TOTAL REVEVNUE] FROM Superstore
 GROUP BY Ship_Mode
 ORDER BY SUM(SALES) DESC;

 /* TOP 10 STATES CONTRIBUTING TO TOTAL REVENUE(SALES) & PROFIT GENERATED  */
 SELECT TOP 10 STATE, ROUND(SUM(SALES), 2) [TOTAL REVENUE ] FROM Superstore
 GROUP BY State
 ORDER BY SUM(SALES) DESC;

 SELECT TOP 10 STATE, ROUND(SUM(Profit), 2) [Total Profit ] FROM Superstore
 GROUP BY State
 ORDER BY SUM(Profit) DESC;

 /* TOP 10 CUSTOMER CONTIBUTING TO REVENUE GENERATED*/
 SELECT TOP 10 Customer_name, Customer_ID, SUM(SALES) [Total Revenue] FROM Superstore
 GROUP BY Customer_Name, Customer_ID
 ORDER BY SUM(SALES) DESC;

 SELECT * FROM Superstore;

 /* TOTAL REVENUE GENERATED ACROSS EACH CATEGORY */
 SELECT Category, SUM(SALES) [Total Revenue] FROM Superstore
 GROUP BY Category
 ORDER BY SUM(SALES) DESC;

 SELECT Category, Sub_Category, SUM(SALES) [Total Revenue] FROM Superstore
 GROUP BY Category, Sub_Category
 HAVING Sub_Category IN ( 'BINDERS', 'ART', 'PHONES', 'BOOKCASES')
 ORDER BY SUM(SALES) DESC;

 /* TOP 10 SUB_CATEGORY CONTRIBUTING TO THE REVENUE GENERATED ACROSS EACH CATEGORY */
 SELECT TOP 10 SUB_CATEGORY,Category, SUM(SALES) [Total Revenue] FROM Superstore
 GROUP BY Sub_Category, Category
 ORDER BY SUM(SALES) DESC;

/* REVENUE GENERATED  FOR ORDER DATE BETWEEN '2013-01-01' AND '2016-12-31' ACROSS EACH STATE */
SELECT Order_Date, State, SUM(Sales) [Total Revenue] FROM Superstore
WHERE Order_Date BETWEEN '2013-01-01' AND '2016-12-31'
GROUP BY State, Order_Date
ORDER BY SUM(SALES) DESC;

/* TOTAL NUMBER OF ORDERS FOR TOP 50 CUSTOMER NAME ACROSS EACH STATE */
WITH DISTINCTSTATES AS (SELECT DISTINCT CUSTOMER_NAME, CUSTOMER_ID, STATE FROM SUPERSTORE) 
SELECT TOP 50 CUSTOMER_NAME, CUSTOMER_ID, STRING_AGG(STATE, ', ') STATES,
(SELECT COUNT(*) FROM Superstore S WHERE S.Customer_ID = D.Customer_ID) AS [Total number of Orders]
FROM DISTINCTSTATES D
GROUP BY Customer_Name, Customer_ID
ORDER BY[Total number of Orders] DESC;
